---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol
spec:
  capacity: 
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "gp2"
  claimRef:
    name: streaming-server-claim0
    namespace: default